### ISSUE TITLE
about eval.py

### ISSUE THREAD

**Issue by DLYL2019** [graspnet/graspnetAPI#24]
请问运行eval.py时，为什么会报以下错误
WARNING:root:Failed to import geometry msgs in rigid_transformations.py.
WARNING:root:Failed to import ros dependencies in rigid_transforms.py
WARNING:root:autolab_core not installed as catkin package, RigidTransform ros methods will be unavailable
Loading data path...: 100%|██████████| 30/30 [00:00<00:00, 124.31it/s]
Loading data path...: 100%|██████████| 30/30 [00:00<00:00, 119.35it/s]
Evaluating scene:121, camera:kinect
Traceback (most recent call last):
  File "*****/graspnetAPI/examples/exam_eval.py", line 23, in <module>
    acc = ge_k.eval_scene(scene_id = sceneId, dump_folder = dump_folder)
  File "*****\graspnetAPI\graspnetAPI\graspnet_eval.py", line 144, in eval_scene
    grasp_list, score_list, collision_mask_list = eval_grasp(grasp_group, model_sampled_list, dexmodel_list, pose_list, config, table=table_trans, voxel_size=0.008, TOP_K = TOP_K)
  File "******\graspnetAPI\graspnetAPI\utils\eval_utils.py", line 336, in eval_grasp
    indices = compute_closest_points(grasp_group.translations, scene)
  File "******\graspnetAPI\graspnetAPI\utils\eval_utils.py", line 129, in compute_closest_points
    dists = compute_point_distance(A, B)
  File "******\graspnetAPI\graspnetAPI\utils\eval_utils.py", line 114, in compute_point_distance
    dists = np.linalg.norm(A-B, axis=-1)
ValueError: operands could not be broadcast together with shapes (2784,1,0) (1,4778,3) 

Process finished with exit code 1

**Comment by chenxi-wang** [comment]
I guess there is something wrong with your input grasp_group. The translation array should be (2784,3) instead of (2784,0).
