### ISSUE TITLE
loadScenePointCloud: RuntimeError

### ISSUE THREAD

**Issue by cww97** [graspnet/graspnetAPI#3]
```
$ python examples/exam_loadGrasp.py
WARNING - 2020-11-27 20:15:17,053 - rigid_transformations - Failed to import geometry msgs in rigid_transformations.py.
WARNING - 2020-11-27 20:15:17,054 - rigid_transformations - Failed to import ros dependencies in rigid_transforms.py
WARNING - 2020-11-27 20:15:17,054 - rigid_transformations - autolab_core not installed as catkin package, RigidTransform ros methods will be unavailable
Loading data path...: 100%|███████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 267.62it/s]
warning: grasp_labels are not given, calling self.loadGraspLabels to retrieve them
Loading grasping labels...: 100%|██████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:06<00:00,  1.34it/s]
warning: collision_labels are not given, calling self.loadCollisionLabels to retrieve them
Loading collision labels...: 100%|█████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.08it/s]
6d grasp:
----------
Grasp Group, Number=90332:
Grasp: score:0.9000000357627869, width:0.11247877031564713, height:0.019999999552965164, depth:0.029999999329447746, translation:[-0.09166837 -0.16910084  0.39480919]
rotation:
[[-0.81045675 -0.57493848  0.11227506]
 [ 0.49874267 -0.77775514 -0.38256073]
 [ 0.30727136 -0.25405255  0.91708326]]
object id:66
Grasp: score:0.9000000357627869, width:0.10030215978622437, height:0.019999999552965164, depth:0.019999999552965164, translation:[-0.09166837 -0.16910084  0.39480919]
rotation:
[[-0.73440629 -0.67870212  0.0033038 ]
 [ 0.64608938 -0.70059127 -0.3028869 ]
 [ 0.20788456 -0.22030747  0.95302087]]
object id:66
Grasp: score:0.9000000357627869, width:0.08487851172685623, height:0.019999999552965164, depth:0.019999999552965164, translation:[-0.10412319 -0.13797761  0.38312319]
rotation:
[[ 0.03316294  0.78667933 -0.61647028]
 [-0.47164679  0.55612749  0.68430358]
 [ 0.88116372  0.26806271  0.38947761]]
object id:66
......
Grasp: score:0.9000000357627869, width:0.11909123510122299, height:0.019999999552965164, depth:0.019999999552965164, translation:[-0.05140382  0.11790846  0.48782501]
rotation:
[[-0.71453273  0.63476181 -0.2941435 ]
 [-0.07400083  0.3495101   0.93400562]
 [ 0.69567728  0.68914449 -0.20276351]]
object id:14
Grasp: score:0.9000000357627869, width:0.10943549126386642, height:0.019999999552965164, depth:0.019999999552965164, translation:[-0.05140382  0.11790846  0.48782501]
rotation:
[[ 0.08162415  0.4604325  -0.88393396]
 [-0.52200603  0.77526748  0.3556262 ]
 [ 0.84902728  0.4323912   0.30362913]]
object id:14
Grasp: score:0.9000000357627869, width:0.11654743552207947, height:0.019999999552965164, depth:0.009999999776482582, translation:[-0.05140382  0.11790846  0.48782501]
rotation:
[[-0.18380146  0.39686993 -0.89928377]
 [-0.61254776  0.66926688  0.42055583]
 [ 0.76876676  0.62815309  0.12008961]]
object id:14
----------
Traceback (most recent call last):
  File "examples/exam_loadGrasp.py", line 27, in <module>
    geometries.append(g.loadScenePointCloud(sceneId = sceneId, annId = annId, camera = 'kinect'))
  File "/home/weiwen/anaconda3/envs/ggcnn/lib/python3.6/site-packages/graspnetAPI/graspnet.py", line 498, in loadScenePointCloud
    cloud.points = o3d.utility.Vector3dVector(points)
RuntimeError
```

**Comment by Fang-Haoshu** [comment]
Fixed
