### ISSUE TITLE
ImportError: numpy.core.multiarray failed to import in Jetson environment

### ISSUE THREAD

**Issue by Aki-zel** [graspnet/graspnetAPI#56]
I encountered an ImportError when running the demo script on my Jetson environment. The error message is as follows:

-> loaded checkpoint log/checkpoint-rs.tar (epoch: 18)
Traceback (most recent call last):
  File "demo.py", line 124, in <module>
    demo(data_dir)
  File "demo.py", line 120, in demo
    vis_grasps(gg, cloud)
  File "demo.py", line 108, in vis_grasps
    gg.nms()
  File "/home/ydfo/.local/lib/python3.8/site-packages/graspnetAPI/grasp.py", line 554, in nms
    from grasp_nms import nms_grasp
  File "grasp_nms.pyx", line 1, in init grasp_nms
ImportError: numpy.core.multiarray failed to import (auto-generated because you didn't call 'numpy.import_array()' after cimporting numpy; use '<void>numpy._import_array' to disable if you are certain you don't need it).
Environment:

Operating System: Ubuntu (Jetson)
Python Version: 3.8
NumPy Version: [1.20.3]
Jetson Model: [Jetson origin Nano]

**Comment by Sprinkle-X** [comment]
hello, that s what i met. Have you solved this?

**Comment by Aki-zel** [comment]
> 你好，我遇到了这个问题。你解决了吗？
You need to clone the GraspNMS GitHub repository (https://github.com/GouMinghao/graspnms), then modify the grasp_nms.pyx file by adding `np._import_array()` after `cimport numpy as np`.

**Comment by Sprinkle-X** [comment]
I tried. But I meet new erro, like "ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject". Need I change other documents? Sorry for this more question.

**Comment by Aki-zel** [comment]
> I tried. But I meet new erro, like "ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject". Need I change other documents? Sorry for this more question.

update you numpy

**Comment by Sprinkle-X** [comment]
> > I tried. But I meet new erro, like "ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject". Need I change other documents? Sorry for this more question.
> 
> update you numpy

But I used numpy 1.20 and python 3.8 as well... T T

**Comment by Aki-zel** [comment]
> > > I tried. But I meet new erro, like "ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject". Need I change other documents? Sorry for this more question.
> > 
> > 
> > update you numpy
> 
> But I used numpy 1.20 and python 3.8 as well... T T

Try using numpy 1.23.5
You can refer to my pip list
[1.txt](https://github.com/user-attachments/files/17943892/1.txt)

**Comment by Sprinkle-X** [comment]
> > > > I tried. But I meet new erro, like "ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject". Need I change other documents? Sorry for this more question.
> > > 
> > > 
> > > update you numpy
> > 
> > 
> > But I used numpy 1.20 and python 3.8 as well... T T
> 
> Try using numpy 1.23.5 You can refer to my pip list [1.txt](https://github.com/user-attachments/files/17943892/1.txt)

!! That s so kind of you. I will try. Thanks a lot :）
