### ISSUE TITLE
exam_eval.py 缺少 dexnet

### ISSUE THREAD

**Issue by cww97** [graspnet/graspnetAPI#6]
```
$ python exam_eval.py 
WARNING - 2020-12-07 15:02:51,492 - rigid_transformations - Failed to import geometry msgs in rigid_transformations.py.
WARNING - 2020-12-07 15:02:51,492 - rigid_transformations - Failed to import ros dependencies in rigid_transforms.py
WARNING - 2020-12-07 15:02:51,492 - rigid_transformations - autolab_core not installed as catkin package, RigidTransform ros methods will be unavailable
Loading data path...: 100%|█████████████████████████████████████████████████████████████████████████████████████████| 90/90 [00:00<00:00, 274.76it/s]
Loading data path...: 100%|█████████████████████████████████████████████████████████████████████████████████████████| 90/90 [00:00<00:00, 275.34it/s]
Evaluating scene:121, camera:kinect
Traceback (most recent call last):
  File "exam_eval.py", line 21, in <module>
    acc = ge_k.eval_scene(scene_id = sceneId, dump_folder = dump_folder)
  File "/home/weiwen/anaconda3/envs/grasp/lib/python3.6/site-packages/graspnetAPI/graspnet_eval.py", line 117, in eval_scene
    model_list, dexmodel_list, _ = self.get_scene_models(scene_id, ann_id=0)
  File "/home/weiwen/anaconda3/envs/grasp/lib/python3.6/site-packages/graspnetAPI/graspnet_eval.py", line 50, in get_scene_models
    dexmodel = pickle.load(f)
ModuleNotFoundError: No module named 'dexnet'
```

**Comment by Fang-Haoshu** [comment]
Sorry, the dexmodel files need to be updated. Please download them again: https://pan.baidu.com/s/1FQz9lmj2vn94rDa3Ihl5VQ
Or you can generate these files according to our documents.
