### ISSUE TITLE
exam_convert.py有两个img show，第二个炸了

### ISSUE THREAD

**Issue by cww97** [graspnet/graspnetAPI#7]
```
$ python examples/exam_convert.py          
WARNING - 2020-12-08 22:49:34,482 - rigid_transformations - Failed to import geometry msgs in rigid_transformations.py.
WARNING - 2020-12-08 22:49:34,482 - rigid_transformations - Failed to import ros dependencies in rigid_transforms.py
WARNING - 2020-12-08 22:49:34,482 - rigid_transformations - autolab_core not installed as catkin package, RigidTransform ros methods will be unavailable
Loading data path...: 100%|███████████████████████████████████████████████████████████████████████████████████| 190/190 [00:00<00:00, 276.30it/s]
Traceback (most recent call last):
  File "examples/exam_convert.py", line 35, in <module>
    grasp = rect_grasp.to_grasp(camera, depth)
  File "/home/weiwen/anaconda3/envs/grasp/lib/python3.6/site-packages/graspnetAPI/grasp.py", line 701, in to_grasp
    depth_2d = depth_method(depths, center, open_point, upper_point) / 1000.0
  File "/home/weiwen/anaconda3/envs/grasp/lib/python3.6/site-packages/graspnetAPI/utils/utils.py", line 558, in center_depth
    return depths[round(center[1]), round(center[0])]
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```

**Comment by GouMinghao** [comment]
Thank you for your report but I can't reproduce your result. Could you please provide more details about this issue.

**Comment by chenxi-wang** [comment]
Hi, the bug is fixed and you can try it again. Thanks!
